// 种子数据。品牌名全部是虚构的，避免demo里出现真实商标。
// 图片是 Unsplash 的公开直链，seed 时下载并由 sharp 处理成本地静态文件。

export const COLORS = {
  black: '#141414',
  ink: '#1B2430',
  charcoal: '#33363A',
  slate: '#4A5157',
  grey: '#8A8D91',
  silver: '#C9CCD1',
  bone: '#E7E2D9',
  cream: '#F1EBE0',
  white: '#F7F7F5',
  sand: '#C9BBA4',
  camel: '#A9855F',
  tan: '#B08A62',
  brown: '#5B4636',
  rust: '#9C5B3C',
  olive: '#5A5F3F',
  forest: '#3E5647',
  navy: '#23314A',
  gold: '#C0A062',
} as const

export type ColorKey = keyof typeof COLORS

export const SIZE_SETS = {
  apparel: ['XS', 'S', 'M', 'L', 'XL'],
  denim: ['28', '30', '32', '34', '36'],
  shoe: ['7', '8', '9', '10', '11', '12'],
  one: [],
} as const

export type SizeSet = keyof typeof SIZE_SETS

export type CategorySeed = {
  slug: string
  name: string
  nameZh: string
  children: { slug: string; name: string; nameZh: string }[]
}

export const CATEGORIES: CategorySeed[] = [
  {
    slug: 'clothing',
    name: 'Clothing',
    nameZh: '服装',
    children: [
      { slug: 'tops', name: 'Tops', nameZh: '上衣' },
      { slug: 'outerwear', name: 'Outerwear', nameZh: '外套' },
      { slug: 'knitwear', name: 'Knitwear', nameZh: '针织' },
      { slug: 'denim', name: 'Denim', nameZh: '牛仔' },
    ],
  },
  {
    slug: 'shoes',
    name: 'Shoes',
    nameZh: '鞋履',
    children: [
      { slug: 'sneakers', name: 'Sneakers', nameZh: '运动鞋' },
      { slug: 'boots', name: 'Boots', nameZh: '靴子' },
      { slug: 'loafers', name: 'Loafers', nameZh: '乐福鞋' },
    ],
  },
  {
    slug: 'bags',
    name: 'Bags',
    nameZh: '箱包',
    children: [
      { slug: 'totes', name: 'Totes', nameZh: '托特包' },
      { slug: 'crossbody', name: 'Crossbody', nameZh: '斜挎包' },
      { slug: 'backpacks', name: 'Backpacks', nameZh: '双肩包' },
    ],
  },
  {
    slug: 'watches',
    name: 'Watches',
    nameZh: '腕表',
    children: [
      { slug: 'automatic', name: 'Automatic', nameZh: '机械表' },
      { slug: 'quartz', name: 'Quartz', nameZh: '石英表' },
      { slug: 'dress-watches', name: 'Dress', nameZh: '正装表' },
    ],
  },
]

export type BrandSeed = { slug: string; name: string; description: string }

export const BRANDS: BrandSeed[] = [
  {
    slug: 'northwell',
    name: 'Northwell',
    description: 'Everyday essentials cut from durable, honest materials. Made to be worn out, not put away.',
  },
  {
    slug: 'aster-co',
    name: 'Aster & Co.',
    description: 'Quiet, feminine tailoring in silk, cashmere and fine cotton.',
  },
  {
    slug: 'halden',
    name: 'Halden',
    description: 'Scandinavian restraint applied to shirting, knitwear and timepieces.',
  },
  {
    slug: 'meridian',
    name: 'Meridian',
    description: 'Technical construction, sportswear roots, no logos.',
  },
  {
    slug: 'corso',
    name: 'Corso',
    description: 'Italian-influenced casualwear at a price that makes sense.',
  },
  {
    slug: 'fieldnote',
    name: 'Fieldnote',
    description: 'Workwear built for weather. Waxed cotton, heavy canvas, solid brass.',
  },
  {
    slug: 'blackwood',
    name: 'Blackwood',
    description: 'Structured outerwear and boots in a strictly dark palette.',
  },
  {
    slug: 'lumen',
    name: 'Lumen',
    description: 'Light layers and soft neutrals for people who dress in a hurry.',
  },
  {
    slug: 'marchand',
    name: 'Marchand',
    description: 'Small-batch leather goods, vegetable tanned and edge painted by hand.',
  },
  {
    slug: 'verity',
    name: 'Verity',
    description: 'Modern classics with an emphasis on drape, weight and proportion.',
  },
]

// 性别归属。列在这两张表里的按各自性别归类，其余一律 UNISEX
// （包、表这类两个入口下都要出现的）。做成两张 slug 表而不是逐条写在商品上，
// 是因为这样调整归类时一眼就能看全，不用在 59 条记录里翻。
const MEN_ONLY = new Set([
  'heavyweight-pocket-tee',
  'linen-camp-shirt',
  'rugby-shirt',
  'waxed-trucker-jacket',
  'bomber',
  'waffle-henley',
  'straight-jean',
  'slim-jean',
  'trail-sneaker',
  'lug-sole-boot',
  'desert-boot',
  'penny-loafer',
  'suede-driver',
  'diver',
  'skeleton-automatic',
  'gmt',
  'pilot-automatic',
  'chronograph',
  'dress-watch',
])

const WOMEN_ONLY = new Set([
  'silk-slip-blouse',
  'boxy-tank',
  'trench',
  'cashmere-turtleneck',
  'cardigan',
  'wide-leg-jean',
  'combat-boot',
  'heeled-loafer',
  'structured-tote',
  'mini-crossbody',
  'minimal-quartz',
  'gold-case',
  'mesh-band',
])

export function genderFor(slug: string): 'MEN' | 'WOMEN' | 'UNISEX' {
  if (MEN_ONLY.has(slug)) return 'MEN'
  if (WOMEN_ONLY.has(slug)) return 'WOMEN'
  return 'UNISEX'
}

export type ProductSeed = {
  slug: string
  title: string
  brand: string
  category: string
  priceCents: number
  compareAtCents?: number
  description: string
  details: string[]
  image: string
  sizes: SizeSet
  colors: ColorKey[]
  featured?: boolean
}

export const PRODUCTS: ProductSeed[] = [
  // ---------- Clothing / Tops ----------
  {
    slug: 'cotton-crew-tee',
    title: 'The Cotton Crew Tee',
    brand: 'northwell',
    category: 'tops',
    priceCents: 3800,
    description:
      'A midweight crewneck in long-staple Peruvian cotton. Cut slightly boxy through the body so it holds its shape after the first wash.',
    details: ['100% Peruvian pima cotton, 180gsm', 'Ribbed collar with taped shoulder seams', 'Machine wash cold, tumble dry low'],
    image: 'photo-1521572163474-6864f9cf17ab',
    sizes: 'apparel',
    colors: ['white', 'black', 'sand'],
    featured: true,
  },
  {
    slug: 'heavyweight-pocket-tee',
    title: 'The Heavyweight Pocket Tee',
    brand: 'fieldnote',
    category: 'tops',
    priceCents: 4500,
    description:
      'Built on a 240gsm loopback jersey that stands up on its own. The patch pocket is bar-tacked at both corners.',
    details: ['100% organic cotton, 240gsm', 'Bar-tacked chest pocket', 'Pre-shrunk, minimal shrinkage'],
    image: 'photo-1618354691373-d851c5c3a990',
    sizes: 'apparel',
    colors: ['bone', 'olive', 'charcoal'],
  },
  {
    slug: 'oxford-shirt',
    title: 'The Oxford Shirt',
    brand: 'halden',
    category: 'tops',
    priceCents: 8800,
    description:
      'A proper oxford, woven on slow looms and washed once so it arrives soft. Unlined collar, single needle side seams.',
    details: ['100% cotton oxford, 140gsm', 'Unlined button-down collar', 'Single needle side seams', 'Mother of pearl buttons'],
    image: 'photo-1596755094514-f87e34085b2c',
    sizes: 'apparel',
    colors: ['white', 'navy'],
    featured: true,
  },
  {
    slug: 'linen-camp-shirt',
    title: 'The Linen Camp Shirt',
    brand: 'corso',
    category: 'tops',
    priceCents: 9800,
    description: 'A relaxed camp collar in washed European linen. Wears cool, creases honestly.',
    details: ['100% washed French linen', 'Camp collar, boxy fit', 'Corozo buttons'],
    image: 'photo-1602810318383-e386cc2a3ccf',
    sizes: 'apparel',
    colors: ['cream', 'slate'],
  },
  {
    slug: 'silk-slip-blouse',
    title: 'The Silk Slip Blouse',
    brand: 'aster-co',
    category: 'tops',
    priceCents: 12800,
    compareAtCents: 16000,
    description: 'Bias-cut sandwashed silk with a fluid drape. Finished with French seams throughout.',
    details: ['100% sandwashed mulberry silk, 19mm', 'Bias cut, French seams', 'Dry clean or hand wash cold'],
    image: 'photo-1594633312681-425c7b97ccd1',
    sizes: 'apparel',
    colors: ['bone', 'ink'],
  },
  {
    slug: 'boxy-tank',
    title: 'The Boxy Tank',
    brand: 'lumen',
    category: 'tops',
    priceCents: 4200,
    description: 'A clean, slightly cropped tank in compact cotton rib. Holds its shape all day.',
    details: ['95% cotton, 5% elastane rib', 'Cropped boxy fit', 'Machine wash cold'],
    image: 'photo-1503341504253-dff4815485f1',
    sizes: 'apparel',
    colors: ['white', 'black'],
  },
  {
    slug: 'rugby-shirt',
    title: 'The Rugby Shirt',
    brand: 'fieldnote',
    category: 'tops',
    priceCents: 9200,
    description: 'Heavy cotton jersey with a twill collar and rubber buttons that will not crack.',
    details: ['100% cotton jersey, 280gsm', 'Reinforced twill collar', 'Rubber buttons'],
    image: 'photo-1489987707025-afc232f7ea0f',
    sizes: 'apparel',
    colors: ['navy', 'cream'],
  },

  // ---------- Clothing / Outerwear ----------
  {
    slug: 'wool-overcoat',
    title: 'The Wool Overcoat',
    brand: 'blackwood',
    category: 'outerwear',
    priceCents: 34800,
    compareAtCents: 42000,
    description:
      'A single breasted overcoat in Italian melton, cut long enough to cover a jacket. Fully lined in cupro.',
    details: ['80% wool, 20% nylon melton, 620gsm', 'Cupro lining', 'Horn buttons', 'Dry clean only'],
    image: 'photo-1544022613-e87ca75a784a',
    sizes: 'apparel',
    colors: ['charcoal', 'camel'],
    featured: true,
  },
  {
    slug: 'waxed-trucker-jacket',
    title: 'The Waxed Trucker Jacket',
    brand: 'fieldnote',
    category: 'outerwear',
    priceCents: 22800,
    description: 'British waxed cotton over a cotton twill body. Gets better the more it gets rained on.',
    details: ['Martexin waxed cotton shell', 'Brass hardware', 'Corduroy-lined collar', 'Re-wax annually, do not machine wash'],
    image: 'photo-1551028719-00167b16eac5',
    sizes: 'apparel',
    colors: ['olive', 'brown'],
  },
  {
    slug: 'puffer',
    title: 'The Puffer',
    brand: 'meridian',
    category: 'outerwear',
    priceCents: 19800,
    description: 'Responsibly sourced 700-fill down in a matte recycled shell. Packs into its own pocket.',
    details: ['700-fill RDS certified down', 'Recycled nylon shell, DWR finish', 'Packs into left hand pocket'],
    image: 'photo-1552374196-c4e7ffc6e126',
    sizes: 'apparel',
    colors: ['black', 'forest'],
  },
  {
    slug: 'trench',
    title: 'The Trench',
    brand: 'marchand',
    category: 'outerwear',
    priceCents: 29800,
    description: 'A softened take on the classic trench, unstructured through the shoulder with a removable belt.',
    details: ['Cotton gabardine with water repellent finish', 'Removable belt', 'Storm flap and throat latch'],
    image: 'photo-1591047139829-d91aecb6caea',
    sizes: 'apparel',
    colors: ['sand', 'ink'],
  },
  {
    slug: 'bomber',
    title: 'The Bomber',
    brand: 'northwell',
    category: 'outerwear',
    priceCents: 17800,
    description: 'Clean MA-1 lines without the patches. Ribbed cuffs, two-way front zip.',
    details: ['Recycled polyester shell', 'Ribbed collar, cuffs and hem', 'Two-way YKK zip'],
    image: 'photo-1608234808654-2a8875faa7fd',
    sizes: 'apparel',
    colors: ['black', 'olive'],
  },

  // ---------- Clothing / Knitwear ----------
  {
    slug: 'merino-crew-sweater',
    title: 'The Merino Crew Sweater',
    brand: 'aster-co',
    category: 'knitwear',
    priceCents: 11800,
    description: 'Fine gauge extra-fine merino, knit in a 12gg for a smooth face that layers under a coat.',
    details: ['100% extra-fine merino wool', '12 gauge knit', 'Hand wash cold, dry flat'],
    image: 'photo-1576566588028-4147f3842f27',
    sizes: 'apparel',
    colors: ['bone', 'navy', 'grey'],
    featured: true,
  },
  {
    slug: 'cashmere-turtleneck',
    title: 'The Cashmere Turtleneck',
    brand: 'verity',
    category: 'knitwear',
    priceCents: 19800,
    compareAtCents: 24500,
    description: 'Grade-A Mongolian cashmere, two-ply, with a collar tall enough to actually fold.',
    details: ['100% grade-A Mongolian cashmere', '2-ply, 7 gauge', 'Hand wash cold, dry flat'],
    image: 'photo-1571945153237-4929e783af4a',
    sizes: 'apparel',
    colors: ['cream', 'black'],
  },
  {
    slug: 'waffle-henley',
    title: 'The Waffle Henley',
    brand: 'halden',
    category: 'knitwear',
    priceCents: 7800,
    description: 'A thermal waffle with a three-button placket. The one you will reach for all winter.',
    details: ['Cotton-modal waffle knit', 'Three button placket', 'Machine wash cold'],
    image: 'photo-1583743814966-8936f5b7be1a',
    sizes: 'apparel',
    colors: ['charcoal', 'rust'],
  },
  {
    slug: 'cardigan',
    title: 'The Cardigan',
    brand: 'lumen',
    category: 'knitwear',
    priceCents: 14800,
    description: 'Relaxed lambswool cardigan with dropped shoulders and deep patch pockets.',
    details: ['100% lambswool', 'Dropped shoulder, oversized fit', 'Patch pockets'],
    image: 'photo-1495121605193-b116b5b9c5fe',
    sizes: 'apparel',
    colors: ['sand', 'forest'],
  },

  // ---------- Clothing / Denim ----------
  {
    slug: 'straight-jean',
    title: 'The Straight Jean',
    brand: 'corso',
    category: 'denim',
    priceCents: 9800,
    description: 'A true straight leg in 13oz rigid Japanese denim. Will fade where you bend.',
    details: ['13oz Japanese selvedge denim', '100% cotton, rigid', 'Button fly', 'Wash inside out, cold'],
    image: 'photo-1618932260643-eee4a2f652a6',
    sizes: 'denim',
    colors: ['navy', 'black'],
  },
  {
    slug: 'relaxed-jean',
    title: 'The Relaxed Jean',
    brand: 'northwell',
    category: 'denim',
    priceCents: 10800,
    description: 'Roomy through the thigh with a clean straight fall from the knee.',
    details: ['12.5oz cotton denim with 1% elastane', 'Relaxed through thigh', 'Zip fly'],
    image: 'photo-1520975916090-3105956dac38',
    sizes: 'denim',
    colors: ['slate', 'ink'],
  },
  {
    slug: 'slim-jean',
    title: 'The Slim Jean',
    brand: 'blackwood',
    category: 'denim',
    priceCents: 11800,
    description: 'Slim without being tight, in a stretch denim that recovers rather than bags out.',
    details: ['11oz stretch denim', '98% cotton, 2% elastane', 'Zip fly'],
    image: 'photo-1554568218-0f1715e72254',
    sizes: 'denim',
    colors: ['black', 'charcoal'],
  },
  {
    slug: 'wide-leg-jean',
    title: 'The Wide Leg Jean',
    brand: 'verity',
    category: 'denim',
    priceCents: 12800,
    description: 'High rise, full leg, cropped just above the ankle. Rigid denim that breaks in fast.',
    details: ['12oz rigid cotton denim', 'High rise, wide leg', 'Cropped inseam'],
    image: 'photo-1611312449408-fcece27cdbb7',
    sizes: 'denim',
    colors: ['navy', 'bone'],
  },

  // ---------- Shoes / Sneakers ----------
  {
    slug: 'court-sneaker',
    title: 'The Court Sneaker',
    brand: 'meridian',
    category: 'sneakers',
    priceCents: 12800,
    description: 'A stripped-back tennis silhouette in full grain leather over a vulcanised rubber sole.',
    details: ['Full grain Italian leather upper', 'Vulcanised rubber outsole', 'Leather-lined footbed'],
    image: 'photo-1542291026-7eec264c27ff',
    sizes: 'shoe',
    colors: ['white', 'black'],
    featured: true,
  },
  {
    slug: 'runner',
    title: 'The Runner',
    brand: 'northwell',
    category: 'sneakers',
    priceCents: 14800,
    description: 'A retro running profile with a modern EVA midsole. Comfortable enough to travel in.',
    details: ['Suede and mesh upper', 'Compression moulded EVA midsole', 'Removable insole'],
    image: 'photo-1549298916-b41d501d3772',
    sizes: 'shoe',
    colors: ['grey', 'navy'],
  },
  {
    slug: 'canvas-low',
    title: 'The Canvas Low',
    brand: 'corso',
    category: 'sneakers',
    priceCents: 7800,
    description: 'Heavy cotton canvas, metal eyelets, gum sole. Nothing else.',
    details: ['14oz cotton canvas upper', 'Natural gum rubber sole', 'Metal eyelets'],
    image: 'photo-1560769629-975ec94e6a86',
    sizes: 'shoe',
    colors: ['bone', 'olive'],
  },
  {
    slug: 'trail-sneaker',
    title: 'The Trail Sneaker',
    brand: 'fieldnote',
    category: 'sneakers',
    priceCents: 16800,
    description: 'A lugged outsole and a protective toe bumper, built for wet pavement and gravel alike.',
    details: ['Ripstop and suede upper', '4mm lug outsole', 'Reinforced toe bumper'],
    image: 'photo-1595950653106-6c9ebd614d3a',
    sizes: 'shoe',
    colors: ['forest', 'sand'],
  },
  {
    slug: 'leather-tennis-shoe',
    title: 'The Leather Tennis Shoe',
    brand: 'halden',
    category: 'sneakers',
    priceCents: 15800,
    description: 'Minimal, unlogoed, and cut low at the ankle. The everyday white sneaker done properly.',
    details: ['Vegetable tanned leather upper', 'Cork footbed', 'Blake stitched'],
    image: 'photo-1600185365483-26d7a4cc7519',
    sizes: 'shoe',
    colors: ['white', 'cream'],
  },
  {
    slug: 'retro-trainer',
    title: 'The Retro Trainer',
    brand: 'lumen',
    category: 'sneakers',
    priceCents: 13800,
    description: 'Seventies proportions, contrast panels, and a soft foam collar.',
    details: ['Suede and nylon upper', 'Foam collar', 'Rubber cupsole'],
    image: 'photo-1465453869711-7e174808ace9',
    sizes: 'shoe',
    colors: ['cream', 'rust'],
  },
  {
    slug: 'slip-on',
    title: 'The Slip-On',
    brand: 'northwell',
    category: 'sneakers',
    priceCents: 8800,
    description: 'Elastic gore, canvas upper, no laces to deal with.',
    details: ['Cotton canvas upper', 'Twin elastic gore', 'Gum rubber sole'],
    image: 'photo-1491553895911-0055eca6402d',
    sizes: 'shoe',
    colors: ['black', 'bone'],
  },

  // ---------- Shoes / Boots ----------
  {
    slug: 'chelsea-boot',
    title: 'The Chelsea Boot',
    brand: 'blackwood',
    category: 'boots',
    priceCents: 26800,
    description: 'Goodyear welted chelsea in oiled suede, resoleable and built on a rounded last.',
    details: ['Oiled suede upper', 'Goodyear welted, resoleable', 'Leather insole, rubber outsole'],
    image: 'photo-1608231387042-66d1773070a5',
    sizes: 'shoe',
    colors: ['brown', 'black'],
    featured: true,
  },
  {
    slug: 'lug-sole-boot',
    title: 'The Lug Sole Boot',
    brand: 'fieldnote',
    category: 'boots',
    priceCents: 29800,
    description: 'A heavy commando sole under a waterproof full grain upper. For actual winters.',
    details: ['Waterproof full grain leather', 'Commando lug outsole', 'Storm welted, sealed seams'],
    image: 'photo-1514989940723-e8e51635b782',
    sizes: 'shoe',
    colors: ['brown', 'ink'],
  },
  {
    slug: 'desert-boot',
    title: 'The Desert Boot',
    brand: 'corso',
    category: 'boots',
    priceCents: 19800,
    description: 'Two eyelets, crepe sole, unlined suede. Light enough for spring.',
    details: ['Unlined suede upper', 'Natural crepe sole', 'Two eyelet lacing'],
    image: 'photo-1552346154-21d32810aba3',
    sizes: 'shoe',
    colors: ['sand', 'brown'],
  },
  {
    slug: 'combat-boot',
    title: 'The Combat Boot',
    brand: 'meridian',
    category: 'boots',
    priceCents: 24800,
    compareAtCents: 31000,
    description: 'Eight eyelets and a side zip so you are not relacing every morning.',
    details: ['Full grain leather upper', 'Side zip with lace closure', 'Oil resistant rubber outsole'],
    image: 'photo-1600269452121-4f2416e55c28',
    sizes: 'shoe',
    colors: ['black'],
  },

  // ---------- Shoes / Loafers ----------
  {
    slug: 'penny-loafer',
    title: 'The Penny Loafer',
    brand: 'marchand',
    category: 'loafers',
    priceCents: 22800,
    description: 'Hand-lasted in Spain, Blake stitched, and cut on a slightly squared last.',
    details: ['Vegetable tanned calf leather', 'Blake stitched construction', 'Leather sole with rubber top piece'],
    image: 'photo-1597045566677-8cf032ed6634',
    sizes: 'shoe',
    colors: ['brown', 'black'],
  },
  {
    slug: 'suede-driver',
    title: 'The Suede Driver',
    brand: 'verity',
    category: 'loafers',
    priceCents: 18800,
    description: 'Soft unstructured suede with a pebbled rubber sole that wraps the heel.',
    details: ['Italian suede upper', 'Pebbled rubber driving sole', 'Fully unlined'],
    image: 'photo-1584735175315-9d5df23860e6',
    sizes: 'shoe',
    colors: ['tan', 'navy'],
  },
  {
    slug: 'heeled-loafer',
    title: 'The Heeled Loafer',
    brand: 'aster-co',
    category: 'loafers',
    priceCents: 20800,
    description: 'A 45mm block heel under a classic loafer upper. Walkable, all day.',
    details: ['Polished calf leather', '45mm stacked block heel', 'Leather lining'],
    image: 'photo-1520639888713-7851133b1ed0',
    sizes: 'shoe',
    colors: ['black', 'camel'],
  },

  // ---------- Bags / Totes ----------
  {
    slug: 'leather-tote',
    title: 'The Leather Tote',
    brand: 'marchand',
    category: 'totes',
    priceCents: 29800,
    description: 'A single piece of vegetable tanned hide, folded and saddle stitched at the corners.',
    details: ['Vegetable tanned full grain leather', 'Hand saddle stitched', 'Fits a 16" laptop', 'Unlined, will patina'],
    image: 'photo-1548036328-c9fa89d128fa',
    sizes: 'one',
    colors: ['brown', 'black'],
    featured: true,
  },
  {
    slug: 'canvas-tote',
    title: 'The Canvas Tote',
    brand: 'corso',
    category: 'totes',
    priceCents: 8800,
    description: '18oz cotton canvas with leather-reinforced handles and a flat interior pocket.',
    details: ['18oz cotton canvas', 'Leather reinforced handles', 'Interior slip pocket'],
    image: 'photo-1584917865442-de89df76afd3',
    sizes: 'one',
    colors: ['bone', 'olive'],
  },
  {
    slug: 'structured-tote',
    title: 'The Structured Tote',
    brand: 'verity',
    category: 'totes',
    priceCents: 34800,
    description: 'Holds its shape empty. Magnetic closure, suede-lined interior, detachable pouch.',
    details: ['Saffiano-textured calf leather', 'Suede lined interior', 'Detachable zip pouch'],
    image: 'photo-1590874103328-eac38a683ce7',
    sizes: 'one',
    colors: ['black', 'camel'],
  },
  {
    slug: 'weekender',
    title: 'The Weekender',
    brand: 'blackwood',
    category: 'totes',
    priceCents: 32800,
    description: 'Two nights of luggage with a separate shoe compartment and a removable strap.',
    details: ['Waxed canvas with leather trim', 'Separate base compartment', 'Removable padded shoulder strap'],
    image: 'photo-1553062407-98eeb64c6a62',
    sizes: 'one',
    colors: ['olive', 'brown'],
  },

  // ---------- Bags / Crossbody ----------
  {
    slug: 'camera-bag',
    title: 'The Camera Bag',
    brand: 'meridian',
    category: 'crossbody',
    priceCents: 17800,
    description: 'Padded, boxy, and just deep enough for a mirrorless body and one lens.',
    details: ['Recycled ripstop with padded walls', 'Adjustable webbing strap', 'Water resistant zips'],
    image: 'photo-1594223274512-ad4803739b7c',
    sizes: 'one',
    colors: ['black', 'forest'],
  },
  {
    slug: 'belt-bag',
    title: 'The Belt Bag',
    brand: 'northwell',
    category: 'crossbody',
    priceCents: 9800,
    description: 'Wear it at the hip or across the chest. One main compartment, one hidden back pocket.',
    details: ['Recycled nylon shell', 'Hidden rear zip pocket', 'Adjustable to 52" strap length'],
    image: 'photo-1566150905458-1bf1fc113f0d',
    sizes: 'one',
    colors: ['black', 'sand'],
  },
  {
    slug: 'mini-crossbody',
    title: 'The Mini Crossbody',
    brand: 'aster-co',
    category: 'crossbody',
    priceCents: 19800,
    description: 'Small enough to disappear, structured enough to stay upright on a table.',
    details: ['Polished calf leather', 'Gold-tone hardware', 'Adjustable and removable strap'],
    image: 'photo-1591561954557-26941169b49e',
    sizes: 'one',
    colors: ['bone', 'black'],
  },
  {
    slug: 'sling',
    title: 'The Sling',
    brand: 'fieldnote',
    category: 'crossbody',
    priceCents: 12800,
    description: 'A single strap pack that swings around to the front without taking it off.',
    details: ['Waxed canvas body', 'Magnetic quick-release buckle', 'Internal key leash'],
    image: 'photo-1611010344444-5f9e4d86a6e1',
    sizes: 'one',
    colors: ['olive', 'charcoal'],
  },

  // ---------- Bags / Backpacks ----------
  {
    slug: 'commuter-backpack',
    title: 'The Commuter Backpack',
    brand: 'halden',
    category: 'backpacks',
    priceCents: 21800,
    description: 'A clean rectangle with a padded 16" laptop sleeve and a luggage pass-through.',
    details: ['Recycled 900D polyester', 'Padded 16" laptop sleeve', 'Luggage pass-through', 'Water repellent finish'],
    image: 'photo-1622560480605-d83c853bc5c3',
    sizes: 'one',
    colors: ['black', 'slate'],
  },
  {
    slug: 'leather-backpack',
    title: 'The Leather Backpack',
    brand: 'marchand',
    category: 'backpacks',
    priceCents: 37800,
    description: 'Full grain hide with solid brass buckles that will outlast the bag.',
    details: ['Full grain vegetable tanned leather', 'Solid brass hardware', 'Cotton canvas lining'],
    image: 'photo-1571689936114-b16146c9570a',
    sizes: 'one',
    colors: ['brown', 'black'],
  },
  {
    slug: 'roll-top-pack',
    title: 'The Roll Top Pack',
    brand: 'lumen',
    category: 'backpacks',
    priceCents: 15800,
    description: 'Roll it down for a day bag, open it up for a grocery run.',
    details: ['Recycled nylon with TPU laminate', 'Roll top with side release buckles', 'Expands from 18L to 26L'],
    image: 'photo-1559563458-527698bf5295',
    sizes: 'one',
    colors: ['sand', 'ink'],
  },

  // ---------- Watches / Automatic ----------
  {
    slug: 'field-automatic',
    title: 'The Field Automatic',
    brand: 'blackwood',
    category: 'automatic',
    priceCents: 59800,
    description: 'A 38mm field watch on a Swiss automatic movement, with a fully lumed dial.',
    details: ['38mm stainless steel case', 'Sellita SW200-1 automatic, 38h reserve', 'Sapphire crystal, AR coated', '100m water resistance'],
    image: 'photo-1524592094714-0f0654e20314',
    sizes: 'one',
    colors: ['black', 'forest'],
    featured: true,
  },
  {
    slug: 'diver',
    title: 'The Diver',
    brand: 'meridian',
    category: 'automatic',
    priceCents: 74800,
    description: '300m rated with a 120-click unidirectional bezel and a screw-down crown.',
    details: ['40mm stainless steel case', '120-click unidirectional bezel', 'Automatic, 41h reserve', '300m water resistance'],
    image: 'photo-1523170335258-f5ed11844a49',
    sizes: 'one',
    colors: ['navy', 'black'],
  },
  {
    slug: 'skeleton-automatic',
    title: 'The Skeleton Automatic',
    brand: 'marchand',
    category: 'automatic',
    priceCents: 89800,
    description: 'An open-worked dial with hand-bevelled bridges, visible from both sides.',
    details: ['40mm case with exhibition caseback', 'Hand-finished bridges', 'Automatic, 42h reserve', '50m water resistance'],
    image: 'photo-1547996160-81dfa63595aa',
    sizes: 'one',
    colors: ['silver', 'gold'],
  },
  {
    slug: 'gmt',
    title: 'The GMT',
    brand: 'verity',
    category: 'automatic',
    priceCents: 84800,
    description: 'A true independent-hour GMT, so you can jump the local hand without stopping the movement.',
    details: ['39mm stainless steel case', 'Independent jumping hour GMT', 'Ceramic 24h bezel', '100m water resistance'],
    image: 'photo-1622434641406-a158123450f9',
    sizes: 'one',
    colors: ['ink', 'silver'],
  },
  {
    slug: 'pilot-automatic',
    title: 'The Pilot Automatic',
    brand: 'northwell',
    category: 'automatic',
    priceCents: 67800,
    description: 'Oversized numerals, a long onion crown, and a thick lumed handset.',
    details: ['41mm stainless steel case', 'Automatic, 38h reserve', 'Domed sapphire crystal', 'Leather strap with quick release'],
    image: 'photo-1533139502658-0198f920d8e8',
    sizes: 'one',
    colors: ['black', 'brown'],
  },

  // ---------- Watches / Quartz ----------
  {
    slug: 'everyday-quartz',
    title: 'The Everyday Quartz',
    brand: 'halden',
    category: 'quartz',
    priceCents: 24800,
    description: 'A 36mm three-hander that runs for four years on one battery.',
    details: ['36mm stainless steel case', 'Swiss quartz, 4 year battery', 'Sapphire crystal', '50m water resistance'],
    image: 'photo-1434056886845-dac89ffe9b56',
    sizes: 'one',
    colors: ['silver', 'bone'],
  },
  {
    slug: 'chronograph',
    title: 'The Chronograph',
    brand: 'corso',
    category: 'quartz',
    priceCents: 34800,
    description: 'A clean two-register chrono with a tachymeter printed on the flange, not the bezel.',
    details: ['40mm stainless steel case', 'Two register quartz chronograph', 'Printed flange tachymeter', '100m water resistance'],
    image: 'photo-1587836374828-4dbafa94cf0e',
    sizes: 'one',
    colors: ['charcoal', 'silver'],
  },
  {
    slug: 'solar',
    title: 'The Solar',
    brand: 'lumen',
    category: 'quartz',
    priceCents: 29800,
    description: 'Charges off any light source. You will never open the caseback.',
    details: ['39mm titanium case', 'Solar movement, 10 month reserve in darkness', 'Sapphire crystal', '100m water resistance'],
    image: 'photo-1509048191080-d2984bad6ae5',
    sizes: 'one',
    colors: ['silver', 'navy'],
  },
  {
    slug: 'digital',
    title: 'The Digital',
    brand: 'fieldnote',
    category: 'quartz',
    priceCents: 16800,
    description: 'A small square digital in brushed steel. Alarm, stopwatch, backlight, nothing else.',
    details: ['34mm brushed steel case', 'Alarm, stopwatch, EL backlight', '50m water resistance'],
    image: 'photo-1508057198894-247b23fe5ade',
    sizes: 'one',
    colors: ['silver', 'black'],
  },
  {
    slug: 'minimal-quartz',
    title: 'The Minimal Quartz',
    brand: 'aster-co',
    category: 'quartz',
    priceCents: 19800,
    description: 'No numerals, no date, no branding on the dial. A 34mm case on a mesh band.',
    details: ['34mm stainless steel case', 'Japanese quartz movement', 'Milanese mesh band', '30m water resistance'],
    image: 'photo-1526045431048-f857369baa09',
    sizes: 'one',
    colors: ['gold', 'silver'],
  },

  // ---------- Watches / Dress ----------
  {
    slug: 'dress-watch',
    title: 'The Dress Watch',
    brand: 'marchand',
    category: 'dress-watches',
    priceCents: 44800,
    description: 'A 7mm thin case that slips under a shirt cuff without catching.',
    details: ['38mm case, 7mm thin', 'Automatic, 40h reserve', 'Alligator-grain leather strap', '30m water resistance'],
    image: 'photo-1548169874-53e85f753f1e',
    sizes: 'one',
    colors: ['black', 'brown'],
  },
  {
    slug: 'gold-case',
    title: 'The Gold Case',
    brand: 'verity',
    category: 'dress-watches',
    priceCents: 69800,
    compareAtCents: 84000,
    description: 'Gold PVD over steel with a warm champagne dial and applied indices.',
    details: ['36mm gold PVD steel case', 'Applied indices, champagne dial', 'Automatic, 38h reserve'],
    image: 'photo-1611591437281-460bfbe1220a',
    sizes: 'one',
    colors: ['gold'],
  },
  {
    slug: 'slim-dress',
    title: 'The Slim Dress Watch',
    brand: 'halden',
    category: 'dress-watches',
    priceCents: 39800,
    description: 'Bauhaus proportions, printed minute track, and a domed sapphire crystal.',
    details: ['38mm stainless steel case', 'Domed sapphire crystal', 'Swiss quartz movement', 'Italian leather strap'],
    image: 'photo-1612817159949-195b6eb9e31a',
    sizes: 'one',
    colors: ['silver', 'ink'],
  },
  {
    slug: 'mesh-band',
    title: 'The Mesh Band Watch',
    brand: 'lumen',
    category: 'dress-watches',
    priceCents: 26800,
    description: 'A slim milanese mesh that adjusts anywhere along its length.',
    details: ['36mm stainless steel case', 'Infinitely adjustable milanese mesh', 'Japanese quartz movement'],
    image: 'photo-1594534475808-b18fc33b045e',
    sizes: 'one',
    colors: ['silver', 'gold'],
  },
]
